version: '3'
services:
  elevator-management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elevatordb
      MYSQL_USER: elevatoruser
      MYSQL_PASSWORD: elevatorpassword
    ports:
      - "3306:3306"
